### ISSUE TITLE
关于测试指标

### ISSUE THREAD

**Issue by szxmachinelearning** [Oliiveralien/MDMS#4]
https://github.com/Oliiveralien/MDMS/blob/9b01c8d83a8ba7523485730b6439d636dd5d6199/models/restoration.py#L50

现在所有方法都能这么玩吗，推理的时候拿真值进行对齐？如果可以的话，直接按像素点对齐像素值，不是直接满分指标了吗？

**Comment by Oliiveralien** [comment]
https://paperswithcode.com/sota/low-light-image-enhancement-on-lol
![sc](https://github.com/Oliiveralien/MDMS/assets/48074765/0e5215e4-0aed-431f-9de4-0b88ed3ec724)
只能无奈地说，打不过就加入。。
此外，MDMS对齐的是均值，有些方法使用均值提升也比较少~
